# This is a basic workflow to help you get started with Actions

name: SyncAppConfiguration

on:
  push:
    branches:
      - 'master'
    paths:
      - 'prod.properties'

jobs:
  syncconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/appconfiguration-sync@v1
        with:
          configurationFile: 'prod.properties'
          format: 'properties'
          # Replace <ConnectionString> with the name of the secret in your repository
          connectionString: "Endpoint=https://apim-config-appc.azconfig.io;Id=vN/j-l9-s0:VJ22Hp5X74HP9IfiNInI;Secret=fmnAODZ45vrBGLc1sF0ed5CrwLR9Ix9ZK0rhSkP1nlI="
          separator: '.'
          prefix: '/application/config.' 
